/**
 * @file plugin-update.ts
 * @description GitHub Release 插件更新包的版本、资产和文件校验工具。
 */

import { strFromU8, unzipSync } from "fflate";

/** Manifest fields validated before a release can replace the installed plugin. */
export interface PluginReleaseManifest {
  id: string;
  version: string;
}

/** Validated executable, style, and manifest files extracted from an install ZIP. */
export interface PluginReleaseFiles {
  manifest: PluginReleaseManifest;
  main: ArrayBuffer;
  styles: ArrayBuffer;
  manifestText: string;
}

/** Public update manifest generated by the release workflow. */
export interface PluginUpdateManifest {
  version: string;
  downloadUrl: string;
  sha256: string;
}

/** Compares two numeric dot-separated versions, ignoring optional prerelease labels. */
export function comparePluginVersions(left: string, right: string): number {
  const parse = (value: string): number[] => value.replace(/^v/i, "").split("-")[0]!.split(".").map((part) => Number(part) || 0);
  const leftParts = parse(left);
  const rightParts = parse(right);
  const length = Math.max(leftParts.length, rightParts.length);
  for (let index = 0; index < length; index += 1) {
    const difference = (leftParts[index] ?? 0) - (rightParts[index] ?? 0);
    if (difference) return difference;
  }
  return 0;
}

/** Parses a release-workflow update manifest and accepts only this plugin's GitHub ZIP URL. */
export function parsePluginUpdateManifest(source: string): PluginUpdateManifest {
  let manifest: PluginUpdateManifest;
  try {
    manifest = JSON.parse(source) as PluginUpdateManifest;
  } catch {
    throw new Error("更新信息文件不是有效 JSON");
  }
  if (!manifest.version || !manifest.downloadUrl || !/^[a-f0-9]{64}$/i.test(manifest.sha256 ?? "")) {
    throw new Error("更新信息文件缺少版本、下载地址或 SHA-256");
  }
  try {
    const url = new URL(manifest.downloadUrl);
    const filename = url.pathname.split("/").at(-1) ?? "";
    if (
      url.protocol !== "https:"
      || url.hostname !== "github.com"
      || !url.pathname.startsWith("/PlanetEditorX/obsidian-mindmap-studio/releases/download/")
      || !/^mindmap-studio-[\w.-]+-install\.zip$/i.test(filename)
    ) throw new Error();
  } catch {
    throw new Error("更新信息文件中的下载地址无效");
  }
  return manifest;
}

/** Verifies a downloaded release archive against the SHA-256 from the update manifest. */
export async function verifyPluginArchiveHash(archive: ArrayBuffer, expectedSha256: string): Promise<boolean> {
  const digest = await crypto.subtle.digest("SHA-256", archive);
  const actual = Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, "0")).join("");
  return actual === expectedSha256.toLowerCase();
}

/** Extracts the three files that an Obsidian plugin may safely self-update. */
export function extractPluginReleaseFiles(archive: ArrayBuffer): PluginReleaseFiles {
  const entries = unzipSync(new Uint8Array(archive));
  const read = (filename: "main.js" | "styles.css" | "manifest.json"): Uint8Array => {
    const entry = Object.entries(entries).find(([path]) => path.split("/").at(-1) === filename)?.[1];
    if (!entry?.length) throw new Error(`更新包缺少 ${filename}`);
    return entry;
  };
  const main = read("main.js");
  const styles = read("styles.css");
  const manifestBytes = read("manifest.json");
  const manifestText = strFromU8(manifestBytes);
  let manifest: PluginReleaseManifest;
  try {
    manifest = JSON.parse(manifestText) as PluginReleaseManifest;
  } catch {
    throw new Error("更新包中的 manifest.json 无效");
  }
  if (!manifest.id || !manifest.version) throw new Error("更新包中的 manifest.json 缺少插件标识或版本");
  const toArrayBuffer = (value: Uint8Array): ArrayBuffer => value.buffer.slice(value.byteOffset, value.byteOffset + value.byteLength) as ArrayBuffer;
  return { manifest, main: toArrayBuffer(main), styles: toArrayBuffer(styles), manifestText };
}
